version: '3.9'

services:
  frontend:
    build: ./frontend
  backend:
    build: ./backend
    command: python manage.py runserver
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./backend:/code
    depends_on:
      - frontend
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
