version: '3.9'

services:
  backend:
    container_name: backend
    extends:
      file: python.yml
      service: pythonenv
    #build: ./backend
        #working_dir: /backend
    entrypoint: python manage.py runserver 0:8000
    expose:
      - "8000"
  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - "6379:6379"
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      # Replace default config with ours
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Place frontend build files
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
