version: '3.9'

services:
  frontend:
    build: ./frontend
  backend:
    #container_name: backend
    #hostname: backend
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend/
    command: python manage.py runserver 0.0.0.0:8000
    #ports:
      #- "8000:8000"
  nginx:
    image: nginx:latest
      #build: ./nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
